-- Mirror the 14 production databases from the runbook
CREATE DATABASE IF NOT EXISTS au;
CREATE DATABASE IF NOT EXISTS datacapture;
CREATE DATABASE IF NOT EXISTS dim;
CREATE DATABASE IF NOT EXISTS finance;
CREATE DATABASE IF NOT EXISTS is_latest;
CREATE DATABASE IF NOT EXISTS jp;
CREATE DATABASE IF NOT EXISTS label;
CREATE DATABASE IF NOT EXISTS mdm;
CREATE DATABASE IF NOT EXISTS nz;
CREATE DATABASE IF NOT EXISTS pbi;
CREATE DATABASE IF NOT EXISTS read;
CREATE DATABASE IF NOT EXISTS stg;
CREATE DATABASE IF NOT EXISTS tech;
CREATE DATABASE IF NOT EXISTS utl;
