apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse_uid
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      username: admin
      defaultDatabase: default
      protocol: native
      secure: false
    secureJsonData:
      password: admin
    editable: true
